name: "deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "setup jdk 11"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      - name: "build for deployment"
        run: "./gradlew distTar"
      - name: "setup ssh"
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DOCKER_HOST_SSH_KEY }}
      - name: "login to ghcr"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "deploy docker"
        run: |
          echo ${{ secrets.DOCKER_HOST_SSH_SIG }} > ~/.ssh/known_hosts
          docker-compose build
          docker-compose push
          DOCKER_HOST="${{ secrets.DOCKER_HOST }}" docker stack deploy --with-registry-auth --compose-file=docker-compose.yml adventure-webui
